stages:

  pre-commmit:
    cmd: pre-commit run --all-files  && chktex -q -V main.tex -n 24 -n 8 -n 1 # Suppresses warnings 8 (dash length), 24 (\labels inside floats), and 1 (trailing whitespace following and command)
    deps:
      - .pre-commit-config.yaml
      - 0-abstract.tex
      - 1-introduction.tex
      - 2-background.tex
      - 3-aft.tex
      - 4-methods.tex
      - 5-results.tex
      - 6-conclusions.tex
      - generate_plots/
      - plots/
  first_run:
    cmd: pdflatex  main.tex
    deps:
      - main.tex
      - 0-abstract.tex
      - 1-introduction.tex
      - 2-background.tex
      - 3-aft.tex
      - 4-methods.tex
      - 5-results.tex
      - 6-conclusions.tex
    outs:
      - main.aux
      - main-blx.bib
      - main.log
      - main.out
      - main.run.xml
  big_run:
    cmd: pdflatex main.tex && bibtex main && pdflatex  main.tex && pdflatex  main.tex 
    deps:
      - main.tex
      - bibliography.bib
      - main-blx.bib
      - main.aux
      - main.log
      - main.out
      - main.run.xml
    outs:
      - main.bbl
      - main.pdf
  arxiv:
    cmd: >-
      python arxiv.py 
      --title "A Training Rate and Survival Heuristic for Inference and Robustness Evaluation (TRASHFIRE)" 
      --directories plots 
      --delete_these_dirs generate_plots data tmp
      --extensions py yaml lock log csv 
      --delete_these_files ".dvcignore" "main.aux" "main.blg" "main.out" "main.run.xml" "main-blx.bib" "main.pdf"
    deps:
      - arxiv.py
      - plots/
      - main.pdf
    outs:
      - "A Training Rate and Survival Heuristic for Inference and Robustness Evaluation (TRASHFIRE).zip"
