stages:
  arxiv:
    cmd: python arxiv.py --directories plots --extensions pdf py yaml csv --title "Survival Analysis for Deep Convolutional Neural Networks"
    deps:
      - arxiv.py
      - plots/
    outs:
      - "Survival Analysis for Deep Convolutional Neural Networks.zip"
