name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
        continue-on-error: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
        continue-on-error: true

#   reproduce:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python 3.9
#       uses: actions/setup-python@v3
#       with:
#         python-version: "3.9"
#     - name: Install dependencies
#       run: |
#         git clone https://github.com/simplymathematics/deckard.git
#         cd deckard && python3 -m pip install .
#         python3 -m pip install pre-commit
#     - name: dvc repro
#       run: dvc repro