name: DVC reproduce
on: [push]
jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        git clone https://github.com/simplymathematics/deckard.git
        cd deckard && python3 -m pip install .
    - name: dvc repro
      run: dvc repro